### ISSUE TITLE
do.create.outlines returns dplyr_error

### ISSUE THREAD

**Issue by mabar1** [ImmuneDynamics/SpectreMAP#6]
Im trying to process IMC data with spectreMAP but run into this error in a couple of scripts, namely in the process of setting up the spatial data object (SpectreMAP - 1 Setup.R) or when attempting to convert TIFF to FCS. I used to pull the repo from tomashhurst but cloned it from immunedynamics. Both Spectre as well as SpecreMAP are fetched today but the error persists and looks like that:

`>spatial.dat <- do.create.outlines(spatial.dat, 'cell.mask')`
Creating polygons, outlines, and centroids using 'stars' method.
Processing masks for ROI BeCeFa_20201109_OT11_s0_p7_r6_a6_ac
although coordinates are longitude/latitude, st_union assumes that they are planar
Error: Problem with `summarise()` column `geometry`.
i `geometry = sf::st_union(geometry)`.
x Evaluation error: TopologyException: side location conflict at 983 113.
i The error occurred in group 1: TEMP_MASK = 0.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In st_is_longlat(x) :
  bounding box has potentially an invalid value range for longlat data

I used the adapted bodenmiller pipeline as described on the page and supply here the .tiff files written in the histocat folder. I did not re-run the pre-processing since beginning of May when I ran it the first time with the adapted pipline.

**Comment by tomashhurst** [comment]
Hi @mabar1 , we've just release Spectre v0.5.0 which has the updated cell segmentation and spatial analysis workflows incorporated directly into Spectre (i.e. SpectreMAP is now redundant). Check out the getting started page to update Spectre, and then check out the spatial analysis page for the update instructions. Essentially you can simply use R to create the objects required to use in Ilastik, rather than having to use Anaconda/Python.
